[project]
name = "cleanse"
version = "0.1.0"
description = "Image Cleanser"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "dotenv>=0.9.9",
    "imagehash>=4.3.2",
    "opencv-python-headless>=4.12.0.88",
    "pillow>=12.0.0",
    "requests>=2.32.5",
]
